image:
    - Visual Studio 2015
    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc.mqttsn.commsdsl
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - CPP_STD: 11
          QT_VER: 5.6.3
        - CPP_STD: 14
          QT_VER: 5.6.3
          

install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - mkdir %BUILD_DIR%
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="C:/Libraries/boost_1_65_1" -DBoost_USE_STATIC_LIBS=ON 
    - nmake
    - mkdir output.build
    - cd output.build
    - echo ------------------------- Building Output -------------------------
    - cmake ../output -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DOPT_QT_DIR=%QTDIR% -DCMAKE_CXX_STANDARD=%CPP_STD% -DOPT_BUILD_TEST=ON -DOPT_BUILD_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=install
    - nmake install
    - IF "%CONFIGURATION%"=="Release" ( nmake deploy_qt )


