dist: bionic
language: cpp
sudo: true
notifications:
  email:
    recipients:
      - arobenko@gmail.com
    on_success: change
    on_failure: always
    
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-4.8  
            - g++-5
      env: _CC=gcc-4.8 _CXX=g++-4.8  _DSL_CC=gcc-5 _DSL_CXX=g++-5
    - os: linux
      addons:
        apt:
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _DSL_CC=${_CC} _DSL_CXX=${_CXX} 
    - os: linux
      addons:
        apt:
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 _DSL_CC=${_CC} _DSL_CXX=${_CXX} 
    - os: linux
      addons:
        apt:
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          packages:
            - g++-8    
      env: _CC=gcc-8 _CXX=g++-8 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          packages:
            - g++-8    
      env: _CC=gcc-8 _CXX=g++-8 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"      
    - os: linux
      env: _CC=gcc-9 _CXX=g++-9 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _USE_GCC9=1 
    - os: linux
      env: _CC=gcc-9 _CXX=g++-9 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _USE_GCC9=1 _BUILD="-DCMAKE_CXX_STANDARD=14"        
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9   
      env: _CC=clang-3.9 _CXX=clang++-3.9 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9   
      env: _CC=clang-3.9 _CXX=clang++-3.9 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0    
      env: _CC=clang-4.0 _CXX=clang++-4.0 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0    
      env: _CC=clang-4.0 _CXX=clang++-4.0 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0    
      env: _CC=clang-6.0 _CXX=clang++-6.0 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0    
      env: _CC=clang-6.0 _CXX=clang++-6.0 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7    
      env: _CC=clang-7 _CXX=clang++-7 _DSL_CC=${_CC} _DSL_CXX=${_CXX} 
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7    
      env: _CC=clang-7 _CXX=clang++-7 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
          packages:
            - clang-8    
      env: _CC=clang-8 _CXX=clang++-8 _DSL_CC=${_CC} _DSL_CXX=${_CXX}
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
          packages:
            - clang-8    
      env: _CC=clang-8 _CXX=clang++-8 _DSL_CC=${_CC} _DSL_CXX=${_CXX} _BUILD="-DCMAKE_CXX_STANDARD=14"
      
before_install:
  - if [ -n "${_USE_GCC9}" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update; sudo apt-get install g++-9; fi
  - sudo apt-get install libqt5serialport5-dev  -y 
  - sudo apt-get install libboost-program-options-dev libboost-filesystem-dev libboost-system-dev -y  

script:
  - echo "------------------ Generating Source ------------------"
  - mkdir build
  - cd build
  - CC=${_DSL_CC} CXX=${_DSL_CXX} cmake ..
  - make
  - echo "------------------ Debug build ------------------"
  - mkdir build.debug
  - cd build.debug
  - CC=${_CC} CXX=${_CXX} cmake ../output -DOPT_BUILD_TEST=ON -DOPT_BUILD_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=install ${_BUILD}
  - make install
  - cd ..
  - echo "------------------ Release build ------------------"  
  - mkdir build.release
  - cd build.release
  - CC=${_CC} CXX=${_CXX} cmake ../output ${_BUILD} -DOPT_BUILD_TEST=ON -DOPT_BUILD_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
  - make install
  - cd ..  
  - echo "------------------ MinSize Release build ------------------"  
  - mkdir build.min_size
  - cd build.min_size
  - CC=${_CC} CXX=${_CXX} cmake ../output ${_BUILD} -DOPT_BUILD_TEST=ON -DOPT_BUILD_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=MinSizeRel
  - make install
  - cd ..    


